Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 20 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, api, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 24, 2023 - 16:02:25
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2023 - 17:23:02
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
[24/Jan/2023 17:25:45] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:26:32] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:26:50] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:26:56] "GET /api/get-nft?format=json HTTP/1.1" 200 95
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2023 - 17:29:20
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
Error: That port is already in use.
[24/Jan/2023 17:29:31] "GET /admin/api/nftcard/ HTTP/1.1" 200 6530
[24/Jan/2023 17:29:31] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /favicon.ico
[24/Jan/2023 17:29:31] "GET /favicon.ico HTTP/1.1" 404 2344
[24/Jan/2023 17:29:36] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:29:55] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:30:02] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:31:06] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:31:12] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:31:12] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 200 94396
[24/Jan/2023 17:31:13] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:32:08] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:32:22] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:32:27] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:32:45] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:33:02] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:34:22] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:34:40] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:35:26] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:35:29] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:35:29] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:36:30] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:36:33] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:36:37] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:36:53] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:36:54] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:37:11] "GET /api/get-nft?format=json HTTP/1.1" 200 95
Not Found: /portal.php
[24/Jan/2023 17:37:18] "GET /portal.php?type=stb&action=handshake&token=&prehash=0&JsHttpRequest=1-xml HTTP/1.1" 404 2420
Not Found: /portal.php
[24/Jan/2023 17:37:18] "GET /portal.php?type=stb&action=handshake&token=&prehash=0&JsHttpRequest=1-xml HTTP/1.1" 404 2420
Not Found: /c/version.js
[24/Jan/2023 17:37:19] "GET /c/version.js HTTP/1.1" 404 2347
Not Found: /stalker_portal/server/load.php
[24/Jan/2023 17:37:19] "GET /stalker_portal/server/load.php?type=stb&action=handshake&token=&prehash=0&JsHttpRequest=1-xml HTTP/1.1" 404 2480
Not Found: /
[24/Jan/2023 17:37:19] "GET / HTTP/1.1" 404 2293
[24/Jan/2023 17:39:34] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:39:39] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:40:23] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:40:23] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:41:08] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:41:09] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 200 94396
[24/Jan/2023 17:42:58] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:42:58] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:43:03] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:43:14] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:44:00] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:44:00] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:46:12] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:46:12] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 200 94396
[24/Jan/2023 17:46:22] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:46:22] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 200 94396
[24/Jan/2023 17:46:35] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:46:49] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:46:49] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:47:21] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:47:32] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:47:40] "GET /api/get-nft?format=json HTTP/1.1" 200 95
[24/Jan/2023 17:47:42] "GET /admin/api/nftcard/1/change/ HTTP/1.1" 200 7384
[24/Jan/2023 17:47:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /favicon.ico
[24/Jan/2023 17:47:43] "GET /favicon.ico HTTP/1.1" 404 2344
[24/Jan/2023 17:47:46] "POST /admin/api/nftcard/1/change/ HTTP/1.1" 302 0
[24/Jan/2023 17:47:46] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7213
[24/Jan/2023 17:47:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:09] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:48:09] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:48:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:18] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:48:18] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:48:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:20] "GET /admin/api/nftcard/ HTTP/1.1" 200 6961
[24/Jan/2023 17:48:20] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:22] "GET /admin/api/nftcard/3/change/ HTTP/1.1" 200 7384
[24/Jan/2023 17:48:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:27] "POST /admin/api/nftcard/3/change/ HTTP/1.1" 302 0
[24/Jan/2023 17:48:27] "GET /admin/api/nftcard/ HTTP/1.1" 200 7172
[24/Jan/2023 17:48:27] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:31] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 6966
[24/Jan/2023 17:48:31] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:48:51] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:48:51] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:48:52] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:49:01] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:49:01] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:49:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:49:12] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:49:12] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:49:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:49:24] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:49:24] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:49:24] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:49:38] "POST /admin/api/nftcard/add/ HTTP/1.1" 302 0
[24/Jan/2023 17:49:38] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 7211
[24/Jan/2023 17:49:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:49:44] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 17:49:44] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:49:44] "GET //media/images/NFT_2_J45novw.png HTTP/1.1" 200 112760
[24/Jan/2023 17:49:44] "GET //media/images/NFT_3_Rbmevsp.png HTTP/1.1" 200 102449
[24/Jan/2023 17:49:44] "GET //media/images/NFT_4_aYt8Gf7.png HTTP/1.1" 200 158067
[24/Jan/2023 17:49:44] "GET //media/images/NFT_5_Gz4pcnW.png HTTP/1.1" 200 121061
[24/Jan/2023 17:49:44] "GET //media/images/NFT_6_qpR7R7r.png HTTP/1.1" 200 137664
[24/Jan/2023 17:49:44] "GET //media/images/NFT_8_zjkdfgd.png HTTP/1.1" 200 46589
[24/Jan/2023 17:49:44] "GET //media/images/NFT_7_ZZQGRnE.png HTTP/1.1" 200 87477
[24/Jan/2023 17:50:18] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 17:50:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 17:51:32] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 17:51:32] "GET //media/images/NFT_5_Gz4pcnW.png HTTP/1.1" 200 121061
[24/Jan/2023 17:51:32] "GET //media/images/NFT_4_aYt8Gf7.png HTTP/1.1" 200 158067
[24/Jan/2023 17:51:32] "GET //media/images/NFT_2_J45novw.png HTTP/1.1" 200 112760
[24/Jan/2023 17:51:32] "GET //media/images/NFT_3_Rbmevsp.png HTTP/1.1" 200 102449
[24/Jan/2023 17:51:32] "GET //media/images/NFT_6_qpR7R7r.png HTTP/1.1" 200 137664
[24/Jan/2023 17:51:32] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 17:51:32] "GET //media/images/NFT_7_ZZQGRnE.png HTTP/1.1" 200 87477
[24/Jan/2023 17:51:32] "GET //media/images/NFT_8_zjkdfgd.png HTTP/1.1" 200 46589
[24/Jan/2023 17:51:58] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 17:51:59] "GET //media/images/NFT_4_aYt8Gf7.png HTTP/1.1" 200 158067
[24/Jan/2023 17:51:59] "GET //media/images/NFT_5_Gz4pcnW.png HTTP/1.1" 200 121061
[24/Jan/2023 17:51:59] "GET //media/images/NFT_6_qpR7R7r.png HTTP/1.1" 200 137664
[24/Jan/2023 17:51:59] "GET //media/images/NFT_3_Rbmevsp.png HTTP/1.1" 200 102449
[24/Jan/2023 17:51:59] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 200 94396
[24/Jan/2023 17:51:59] "GET //media/images/NFT_2_J45novw.png HTTP/1.1" 200 112760
[24/Jan/2023 17:51:59] "GET //media/images/NFT_7_ZZQGRnE.png HTTP/1.1" 200 87477
[24/Jan/2023 17:51:59] "GET //media/images/NFT_8_zjkdfgd.png HTTP/1.1" 200 46589
[24/Jan/2023 18:02:16] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 18:02:16] "GET //media/images/NFT_2_J45novw.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:16] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:16] "GET //media/images/NFT_3_Rbmevsp.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:16] "GET //media/images/NFT_4_aYt8Gf7.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:16] "GET //media/images/NFT_5_Gz4pcnW.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:16] "GET //media/images/NFT_6_qpR7R7r.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:17] "GET //media/images/NFT_8_zjkdfgd.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:17] "GET //media/images/NFT_7_ZZQGRnE.png HTTP/1.1" 304 0
[24/Jan/2023 18:02:19] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 18:02:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /favicon.ico
[24/Jan/2023 18:02:20] "GET /favicon.ico HTTP/1.1" 404 2344
[24/Jan/2023 18:39:31] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 18:39:32] "GET //media/images/NFT_2_J45novw.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:32] "GET //media/images/NFT_1_IeEuala.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:32] "GET //media/images/NFT_3_Rbmevsp.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:33] "GET //media/images/NFT_4_aYt8Gf7.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:33] "GET //media/images/NFT_6_qpR7R7r.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:33] "GET //media/images/NFT_5_Gz4pcnW.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:33] "GET //media/images/NFT_8_zjkdfgd.png HTTP/1.1" 304 0
[24/Jan/2023 18:39:33] "GET //media/images/NFT_7_ZZQGRnE.png HTTP/1.1" 304 0
[24/Jan/2023 18:43:42] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 18:43:49] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 18:43:49] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 18:43:51] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 18:43:54] "GET /api/get-nft?format=json HTTP/1.1" 200 753
[24/Jan/2023 18:45:10] "GET /api/get-nft?tag=music HTTP/1.1" 200 6829
[24/Jan/2023 18:45:10] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[24/Jan/2023 18:45:10] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[24/Jan/2023 18:45:10] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[24/Jan/2023 18:45:10] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[24/Jan/2023 18:45:10] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[24/Jan/2023 18:45:10] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[24/Jan/2023 18:45:26] "GET /api/get-nft?tag=music&limit=1 HTTP/1.1" 200 5531
[24/Jan/2023 18:45:34] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 18:45:34] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 18:46:11] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 18:46:11] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[24/Jan/2023 18:46:15] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 6966
[24/Jan/2023 18:46:16] "GET /admin/api/nftcard/add/ HTTP/1.1" 200 6966
[24/Jan/2023 18:46:20] "GET /admin/api/nftcard HTTP/1.1" 301 0
[24/Jan/2023 18:46:20] "GET /admin/api/nftcard/ HTTP/1.1" 200 8036
[24/Jan/2023 18:46:20] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
/var/www/html/NFT.SHOP/nft_back/api/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): api.
Run 'python manage.py migrate' to apply them.
January 24, 2023 - 18:55:14
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
Internal Server Error: /admin/api/nftcard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: api_nftcard.tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: api_nftcard.tag
[24/Jan/2023 18:55:44] "GET /admin/api/nftcard/ HTTP/1.1" 500 149961
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): api.
Run 'python manage.py migrate' to apply them.
January 24, 2023 - 18:56:20
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
Error: That port is already in use.
Internal Server Error: /admin/api/nftcard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: api_nftcard.tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: api_nftcard.tag
[24/Jan/2023 18:56:23] "GET /admin/api/nftcard/ HTTP/1.1" 500 149961
Internal Server Error: /admin/api/nftcard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: api_nftcard.tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: api_nftcard.tag
[24/Jan/2023 18:56:29] "GET /admin/api/nftcard/ HTTP/1.1" 500 149961
[24/Jan/2023 18:56:34] "GET /admin/ HTTP/1.1" 200 7202
Internal Server Error: /admin/api/nftcard/8/change/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: api_nftcard.tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1893, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1750, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 1773, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/options.py", line 864, in get_object
    return queryset.get(**{field.name: object_id})
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: api_nftcard.tag
[24/Jan/2023 18:56:40] "GET /admin/api/nftcard/8/change/ HTTP/1.1" 500 167238
[24/Jan/2023 18:56:42] "GET /admin/ HTTP/1.1" 200 7202
/var/www/html/NFT.SHOP/nft_back/nft_back/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2023 - 18:59:02
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
/var/www/html/NFT.SHOP/nft_back/api/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2023 - 18:59:09
Django version 4.1.5, using settings 'nft_back.settings'
Starting development server at http://45.10.42.11:8001/
Quit the server with CONTROL-C.
